[package]
name = "mergesort"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"

[profile.release]
# Small binary
opt-level = "s"
lto = true
codegen-units = 1