[package]
name = "selection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.5.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "rselect"
harness = false