name: Succinct Code Counter

# Controls when the workflow will run
on:
 # schedule:
      # Every 7 Days
      #- cron: 0 0 */7 * *
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

    
jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: A job to count the lines of code.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2
        with:
          args: ${{ env.workspace }} -i html,rs,py,c,sml,asm,rb -f html-table
      - name: wite to File
        run: |
          echo "${{ steps.scc.outputs.scc }}" > .github/loc_table.html
        shell: bash
      - name: Get Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Update Readme
        run: python .github/update_table.py
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Automatic update of README.md table" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
